// Golden simulation: runs a bot-only game in the ORIGINAL OpenFrontIO
// TypeScript and records snapshots the Luau port must reproduce exactly.
//
// Usage (from the OpenFrontIO checkout):
//   cd ../OpenFrontIO && npx tsx ../OpenFrontRoblox/tools/golden-sim.mts
//
// Writes tests/SimVectors.luau. The scenario only uses systems the port has
// (factories disabled, no nations, no humans; boats ON), so any
// difference is a porting bug, not a missing feature.

import crypto from "node:crypto";
import fs from "node:fs";
import path from "node:path";
import { fileURLToPath, pathToFileURL } from "node:url";

const here = path.dirname(fileURLToPath(import.meta.url));
const upstream = process.env.OPENFRONT_DIR ?? path.resolve(here, "../../OpenFrontIO");
const imp = (p: string) => import(pathToFileURL(path.join(upstream, p)).href);

const { Config } = await imp("src/core/configuration/Config.ts");
const { createGame } = await imp("src/core/game/GameImpl.ts");
const { genTerrainFromBin } = await imp("src/core/game/TerrainMapLoader.ts");
const { Executor } = await imp("src/core/execution/ExecutionManager.ts");
const { SpawnTimerExecution } = await imp("src/core/execution/SpawnTimerExecution.ts");
const { WinCheckExecution } = await imp("src/core/execution/WinCheckExecution.ts");

export const SCENARIO = {
  gameID: "golden01",
  mapDir: "world",
  bots: 40,
  ticks: 1500,
  snapshots: [0, 100, 200, 201, 202, 205, 210, 250, 300, 400, 600, 800, 1000, 1200, 1500],
  // Factories only (rail network not ported yet); transport ships ON.
  disabledUnits: ["Factory"],
};

const gameConfig = {
  gameMap: "World",
  difficulty: "Medium",
  donateGold: false,
  donateTroops: false,
  gameType: "Private",
  gameMode: "Free For All",
  gameMapSize: "Compact",
  bots: SCENARIO.bots,
  randomSpawn: false,
  infiniteGold: false,
  infiniteTroops: false,
  instantBuild: false,
  disabledUnits: SCENARIO.disabledUnits,
  nations: "disabled",
};

const mapDir = path.join(upstream, "resources/maps", SCENARIO.mapDir);
const manifest = JSON.parse(fs.readFileSync(path.join(mapDir, "manifest.json"), "utf8"));
const gameMap = await genTerrainFromBin(manifest.map4x, new Uint8Array(fs.readFileSync(path.join(mapDir, "map4x.bin"))));
const miniMap = await genTerrainFromBin(manifest.map16x, new Uint8Array(fs.readFileSync(path.join(mapDir, "map16x.bin"))));

const config = new Config(gameConfig, null, false);
const game = createGame([], [], gameMap, miniMap, config, undefined);
const executor = new Executor(game, SCENARIO.gameID, undefined, []);

// GameRunner.init() for this config.
game.addExecution(new SpawnTimerExecution());
game.addExecution(...executor.spawnTribes(SCENARIO.bots));
game.addExecution(new WinCheckExecution());

type Snapshot = {
  tick: number;
  stateSha: string;
  hash: number;
  alive: number;
  totalOwned: number;
  players: { name: string; id: string; tiles: number; troops: number; gold: number }[];
};

function snapshot(tick: number): Snapshot {
  const state: Uint16Array = game.map().tileStateBuffer();
  const stateSha = crypto
    .createHash("sha256")
    .update(Buffer.from(state.buffer, state.byteOffset, state.byteLength))
    .digest("hex");
  const all = game.allPlayers();
  let totalOwned = 0;
  for (const p of all) totalOwned += p.numTilesOwned();
  return {
    tick,
    stateSha,
    hash: (game as unknown as { hash(): number }).hash(),
    alive: game.players().length,
    totalOwned,
    // Every player, in creation order, so the first differing one is obvious.
    players: all.map((p: any) => ({
      name: p.name(),
      id: p.id(),
      tiles: p.numTilesOwned(),
      troops: p.troops(),
      gold: Number(p.gold()),
    })),
  };
}

const snaps: Snapshot[] = [];
const want = new Set(SCENARIO.snapshots);
const t0 = performance.now();
for (let tick = 0; tick <= SCENARIO.ticks; tick++) {
  if (want.has(tick)) snaps.push(snapshot(tick));
  if (tick < SCENARIO.ticks) game.executeNextTick();
}
const ms = performance.now() - t0;

const luaStr = (s: string) => JSON.stringify(s);
const lua = `-- AUTO-GENERATED by tools/golden-sim.mts from upstream OpenFrontIO. Do not edit.
-- Upstream ran ${SCENARIO.ticks} ticks in ${ms.toFixed(0)} ms.
return {
\tgameID = ${luaStr(SCENARIO.gameID)},
\tmap = "World",
\tbots = ${SCENARIO.bots},
\tticks = ${SCENARIO.ticks},
\t-- Units ever created (boats) by the final tick.
\tunitsCreated = ${(game as any)._nextUnitID - 1},
\tconfig = {
\t\tgameMap = "World", difficulty = "Medium", donateGold = false, donateTroops = false,
\t\tgameType = "Private", gameMode = "Free For All", gameMapSize = "Compact",
\t\tbots = ${SCENARIO.bots}, randomSpawn = false, infiniteGold = false, infiniteTroops = false,
\t\tinstantBuild = false, disabledUnits = { ${SCENARIO.disabledUnits.map((u) => JSON.stringify(u)).join(", ")} }, nations = "disabled",
\t},
\tsnapshots = {
${snaps
  .map(
    (s) =>
      `\t\t{ tick = ${s.tick}, stateSha = ${luaStr(s.stateSha)}, hash = ${s.hash}, alive = ${s.alive}, totalOwned = ${s.totalOwned}, players = {\n${s.players
        .map((p) => `\t\t\t{ name = ${luaStr(p.name)}, id = ${luaStr(p.id)}, tiles = ${p.tiles}, troops = ${p.troops}, gold = ${p.gold} },`)
        .join("\n")}\n\t\t} },`,
  )
  .join("\n")}
\t},
}
`;
const outFile = path.resolve(here, "../tests/SimVectors.luau");
fs.writeFileSync(outFile, lua);
console.log(`upstream: ${SCENARIO.ticks} ticks in ${ms.toFixed(0)} ms, ${snaps.length} snapshots -> ${path.relative(process.cwd(), outFile)}`);
const last = snaps[snaps.length - 1];
console.log(`tick ${last.tick}: alive=${last.alive} owned=${last.totalOwned} hash=${last.hash} sha=${last.stateSha.slice(0, 12)}`);
