// Golden water-pathfinding vectors from the ORIGINAL OpenFrontIO TypeScript.
//
// Usage (from the OpenFrontIO checkout):
//   cd ../OpenFrontIO && npx tsx ../OpenFrontRoblox/tools/golden-paths.mts
//
// Writes tests/PathVectors.luau: a fingerprint of the minimap water graph
// (nodes, edges, costs, components) and boat routes (full chain: MiniMap ->
// ShoreCoercing -> Smoothing -> ComponentCheck -> hierarchical A*) between
// seeded random shore / water tiles on World.

import crypto from "node:crypto";
import fs from "node:fs";
import path from "node:path";
import { fileURLToPath, pathToFileURL } from "node:url";

const here = path.dirname(fileURLToPath(import.meta.url));
const upstream = process.env.OPENFRONT_DIR ?? path.resolve(here, "../../OpenFrontIO");
const imp = (p: string) => import(pathToFileURL(path.join(upstream, p)).href);

const { Config } = await imp("src/core/configuration/Config.ts");
const { createGame } = await imp("src/core/game/GameImpl.ts");
const { genTerrainFromBin } = await imp("src/core/game/TerrainMapLoader.ts");
const { WaterPathFinder } = await imp("src/core/pathfinding/PathFinder.ts");
const { PseudoRandom } = await imp("src/core/PseudoRandom.ts");

const mapDir = path.join(upstream, "resources/maps/world");
const manifest = JSON.parse(fs.readFileSync(path.join(mapDir, "manifest.json"), "utf8"));
const gameMap = await genTerrainFromBin(manifest.map4x, new Uint8Array(fs.readFileSync(path.join(mapDir, "map4x.bin"))));
const miniMap = await genTerrainFromBin(manifest.map16x, new Uint8Array(fs.readFileSync(path.join(mapDir, "map16x.bin"))));
const config = new Config(
  {
    gameMap: "World",
    difficulty: "Medium",
    donateGold: false,
    donateTroops: false,
    gameType: "Private",
    gameMode: "Free For All",
    gameMapSize: "Compact",
    bots: 0,
    randomSpawn: false,
    infiniteGold: false,
    infiniteTroops: false,
    instantBuild: false,
    disabledUnits: [],
    nations: "disabled",
  },
  null,
  false,
);
const game = createGame([], [], gameMap, miniMap, config, undefined);
const graph = game.miniWaterGraph();

const sha = (s: string) => crypto.createHash("sha256").update(s).digest("hex");
const nodes = graph.getAllNodes().map((n: any) => `${n.id},${n.x},${n.y},${n.tile},${n.componentId}`).join(";");
const edges = graph.getAllEdges().map((e: any) => `${e.id},${e.nodeA},${e.nodeB},${e.cost},${e.clusterX},${e.clusterY}`).join(";");
const clusters: string[] = [];
for (let cy = 0; cy < graph.clustersY; cy++) {
  for (let cx = 0; cx < graph.clustersX; cx++) {
    clusters.push(graph.getCluster(cx, cy).nodeIds.join(","));
  }
}

// Seeded endpoints: shore land tiles and ocean tiles (what boats use).
const rand = new PseudoRandom(20260923);
const W = gameMap.width();
const H = gameMap.height();
function pick(pred: (t: number) => boolean): number {
  for (;;) {
    const t = gameMap.ref(rand.nextInt(0, W), rand.nextInt(0, H));
    if (pred(t)) return t;
  }
}
const isShore = (t: number) => gameMap.isShore(t);
const isOcean = (t: number) => gameMap.isOcean(t);
const queries: { from: number; to: number; len: number; hash: string; head: number[]; tail: number[] }[] = [];
for (let i = 0; i < 80; i++) {
  const from = i % 3 === 0 ? pick(isOcean) : pick(isShore);
  const to = i % 2 === 0 ? pick(isShore) : pick(isOcean);
  const pf = new WaterPathFinder(game);
  const p: number[] | null = pf.findPath(from, to);
  queries.push({
    from,
    to,
    len: p === null ? -1 : p.length,
    hash: p === null ? "" : sha(p.join(",")),
    head: p === null ? [] : p.slice(0, 5),
    tail: p === null ? [] : p.slice(-5),
  });
}

const lua = `-- AUTO-GENERATED by tools/golden-paths.mts from upstream OpenFrontIO. Do not edit.
return {
\tgraph = {
\t\tnodeCount = ${graph.nodeCount},
\t\tedgeCount = ${graph.edgeCount},
\t\tnodesSha = ${JSON.stringify(sha(nodes))},
\t\tedgesSha = ${JSON.stringify(sha(edges))},
\t\tclustersSha = ${JSON.stringify(sha(clusters.join("|")))},
\t\tlandComponentId = ${graph.getComponentId(miniMap.ref(250, 100))},
\t},
\tqueries = {
${queries
  .map(
    (q) =>
      `\t\t{ from = ${q.from}, to = ${q.to}, len = ${q.len}, hash = ${JSON.stringify(q.hash)}, head = { ${q.head.join(", ")} }, tail = { ${q.tail.join(", ")} } },`,
  )
  .join("\n")}
\t},
}
`;
fs.writeFileSync(path.resolve(here, "../tests/PathVectors.luau"), lua);
const found = queries.filter((q) => q.len >= 0).length;
console.log(`graph: ${graph.nodeCount} nodes, ${graph.edgeCount} edges; ${found}/${queries.length} routes found`);
