// Rasterises upstream HUD icons (resources/images/*.svg, CC BY-SA 4.0) into
// raw RGBA bitmaps for EditableImage, since Roblox cannot draw SVG.
//
// Usage (once: `npm install` in tools/):
//   node tools/pack-icons.mjs [path/to/OpenFrontIO]
// Writes src/shared/Data/Icons.luau: { [name] = { size = n, rgba = base64 } }.

import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";
import { Resvg } from "@resvg/resvg-js";

const here = path.dirname(fileURLToPath(import.meta.url));
const upstream = process.argv[2] ?? process.env.OPENFRONT_DIR ?? path.resolve(here, "../../OpenFrontIO");
const SIZE = 48; // px, square; icons are fitted and centred

// name -> upstream file (HotbarIcons.ts + ControlPanel swordIcon).
const ICONS = {
  soldier: "SoldierIcon.svg",
  goldCoin: "GoldCoinIcon.svg",
  sword: "SwordIcon.svg",
  city: "CityIconWhite.svg",
  factory: "FactoryIconWhite.svg",
  port: "PortIcon.svg",
  defensePost: "ShieldIconWhite.svg",
  missileSilo: "MissileSiloIconWhite.svg",
  samLauncher: "SamLauncherIconWhite.svg",
  warship: "BattleshipIconWhite.svg",
  atomBomb: "NukeIconWhite.svg",
  hydrogenBomb: "MushroomCloudIconWhite.svg",
  mirv: "MIRVIcon.svg",
  // Radial menu (RadialMenuElements.ts / RadialMenu.ts).
  boat: "BoatIconWhite.svg",
  build: "BuildIconWhite.svg",
  info: "InfoIcon.svg",
  alliance: "AllianceIconWhite.svg",
  x: "XIcon.svg",
  back: "BackIconWhite.svg",
  swordWhite: "SwordIconWhite.svg",
  target: "TargetIconWhite.svg",
  traitor: "TraitorIconWhite.svg",
  donateGold: "DonateGoldIconWhite.svg",
  donateTroop: "DonateTroopIconWhite.svg",
  emoji: "EmojiIconWhite.svg",
  chat: "ChatIconWhite.svg",
  // Player panel (PlayerPanel.ts) and name icons (PlayerIcons.ts).
  stopTrading: "StopIconWhite.svg",
  startTrading: "TradingIconWhite.svg",
  allianceRequest: "AllianceRequestWhiteIcon.svg",
  crown: "CrownIcon.svg",
  disconnected: "DisconnectedIcon.svg",
  embargo: "EmbargoWhiteIcon.svg",
  nukeRed: "NukeIconRed.svg",
  targetRed: "TargetIcon.svg",
};

function render(file) {
  const svg = fs.readFileSync(path.join(upstream, "resources/images", file), "utf8");
  const probe = new Resvg(svg);
  const { width, height } = probe;
  const fitWidth = width >= height;
  const r = new Resvg(svg, { fitTo: fitWidth ? { mode: "width", value: SIZE } : { mode: "height", value: SIZE } });
  const img = r.render();
  // Centre into a SIZE x SIZE canvas.
  const out = Buffer.alloc(SIZE * SIZE * 4);
  const ox = Math.floor((SIZE - img.width) / 2);
  const oy = Math.floor((SIZE - img.height) / 2);
  const px = img.pixels; // premultiplied RGBA (tiny-skia); un-premultiply below
  for (let y = 0; y < img.height; y++) {
    for (let x = 0; x < img.width; x++) {
      const s = (y * img.width + x) * 4;
      const d = ((y + oy) * SIZE + (x + ox)) * 4;
      const a = px[s + 3];
      for (let c = 0; c < 3; c++) out[d + c] = a === 0 ? 0 : Math.min(255, Math.round((px[s + c] * 255) / a));
      out[d + 3] = a;
    }
  }
  return out;
}

let lua = `-- AUTO-GENERATED by tools/pack-icons.mjs from upstream OpenFrontIO
-- resources/images (CC BY-SA 4.0, © OpenFront and Contributors). Do not edit.
-- Each icon: ${SIZE}x${SIZE} straight (non-premultiplied) RGBA, base64.
return {
`;
for (const [name, file] of Object.entries(ICONS)) {
  const rgba = render(file);
  lua += `\t${name} = { size = ${SIZE}, file = ${JSON.stringify(file)}, rgba = "${rgba.toString("base64")}" },\n`;
}
lua += "}\n";
const dst = path.resolve(here, "../src/shared/Data/Icons.luau");
fs.writeFileSync(dst, lua);
console.log(`wrote ${dst} (${Object.keys(ICONS).length} icons, ${(lua.length / 1024).toFixed(0)} KB)`);
