// Packs UI translations into a Luau module (read by client Lang.luau).
//
// Usage: node tools/pack-lang.mjs
//
// Sources: every string literal the client displays (src/client/*.luau) plus
// tools/lang/*.json (our own translations, keyed by English source). An
// entry's Key is the upstream en.json key when the English text matches one,
// so upstream translations (resources/lang, CC BY-SA 4.0) fill the values.
//
// Output: src/shared/Data/Translations.luau

import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const here = path.dirname(fileURLToPath(import.meta.url));
const upstream = process.env.OPENFRONT_DIR ?? path.resolve(here, "../../OpenFrontIO");
const langDir = path.join(upstream, "resources/lang");

// Roblox locale id -> upstream file. Polish is the priority language; the
// others are upstream files with >= 80 % coverage.
const LOCALES = { pl: "pl", de: "de", fr: "fr", pt: "pt-BR", ru: "ru", ja: "ja", ko: "ko", vi: "vi", "zh-tw": "zh-TW" };

function flat(o, pre = "", out = {}) {
  for (const k in o) {
    if (o[k] && typeof o[k] === "object") flat(o[k], pre + k + ".", out);
    else out[pre + k] = o[k];
  }
  return out;
}
const read = (f) => JSON.parse(fs.readFileSync(f, "utf8"));
const en = flat(read(path.join(langDir, "en.json")));
const upstreamLang = Object.fromEntries(Object.entries(LOCALES).map(([id, f]) => [id, flat(read(path.join(langDir, `${f}.json`)))]));
const extra = {};
for (const id of Object.keys(LOCALES)) {
  const f = path.join(here, "lang", `${id}.json`);
  extra[id] = fs.existsSync(f) ? read(f) : {};
  delete extra[id]._comment;
}

const keyOf = new Map();
for (const k in en) if (!keyOf.has(en[k])) keyOf.set(en[k], k);

// Strings the client shows.
const sources = new Set();
const clientDir = path.resolve(here, "../src/client");
for (const f of fs.readdirSync(clientDir)) {
  for (const line of fs.readFileSync(path.join(clientDir, f), "utf8").split("\n")) {
    if (/^\s*--/.test(line)) continue;
    for (const m of line.matchAll(/"((?:[^"\\\n]|\\.){2,})"/g)) if (keyOf.has(m[1])) sources.add(m[1]);
  }
}
// Map names shown in the lobby.
const catalog = fs.readFileSync(path.resolve(here, "../src/shared/Data/MapCatalog.luau"), "utf8");
for (const m of catalog.matchAll(/"([^"\n]{2,})"/g)) if (keyOf.has(m[1])) sources.add(m[1]);
for (const id in extra) for (const s in extra[id]) sources.add(s);

const lua = (s) => JSON.stringify(s); // JSON string escapes are valid Luau
const rows = [];
let n = 0;
const count = Object.fromEntries(Object.keys(LOCALES).map((id) => [id, 0]));
for (const source of [...sources].sort()) {
  const key = keyOf.get(source) ?? `rbx.${++n}`;
  const values = [];
  for (const id of Object.keys(LOCALES)) {
    let v = extra[id][source];
    if (v === undefined && keyOf.has(source)) {
      const u = upstreamLang[id][key];
      if (typeof u === "string" && u !== source) v = u;
    }
    if (v !== undefined) {
      values.push(`[${lua(id)}] = ${lua(v)}`);
      count[id]++;
    }
  }
  if (values.length === 0) continue;
  rows.push(`\t{ key = ${lua(key)}, source = ${lua(source)}, values = { ${values.join(", ")} } },`);
}

const out = `-- AUTO-GENERATED by tools/pack-lang.mjs. Do not edit.
-- UI translations (upstream OpenFrontIO resources/lang, CC BY-SA 4.0, plus
-- tools/lang/*.json). Applied to the GUI by client Lang.luau.
return {
${rows.join("\n")}
}
`;
fs.writeFileSync(path.resolve(here, "../src/shared/Data/Translations.luau"), out);
console.log(`Translations.luau: ${rows.length} entries, ${(out.length / 1024).toFixed(0)} KB`, count);
