// Packs a curated set of country flags from upstream resources/flags
// (CC BY-SA 4.0, attribution: OpenFront) into one RGBA atlas for the
// "flag next to your name" cosmetic.
//
// Usage: node tools/pack-flags.mjs
// Output: src/shared/Data/Flags.luau
//   { w, h, cols, codes = { code, ... }, names = { [code] = name }, rgba = base64 }
// Only present-day countries (ISO 3166 codes): historical and political
// flags are left out on purpose.

import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";
import { Resvg } from "@resvg/resvg-js";

const here = path.dirname(fileURLToPath(import.meta.url));
const upstream = process.env.OPENFRONT_DIR ?? path.resolve(here, "../../OpenFrontIO");
const W = 24, H = 16, COLS = 12;

const CODES = [
  "pl", "us", "gb", "de", "fr", "it", "es", "pt", "nl", "be", "ch", "at", "se", "no", "dk", "fi",
  "ie", "is", "cz", "sk", "hu", "ro", "bg", "gr", "hr", "si", "rs", "ba", "ua", "lt", "lv", "ee",
  "tr", "ru", "by", "md", "ge", "am", "az", "kz", "ca", "mx", "br", "ar", "cl", "co", "pe", "ve",
  "uy", "py", "bo", "ec", "cu", "jm", "cn", "jp", "kr", "in", "pk", "bd", "id", "my", "sg", "th",
  "vn", "ph", "au", "nz", "sa", "ae", "qa", "il", "ps", "eg", "ma", "dz", "tn", "ng", "gh", "ke",
  "et", "za", "tz", "ug", "cm", "sn", "ci", "ir", "iq", "af", "mn", "np", "lk", "eu", "un", "aq",
];

const countries = JSON.parse(fs.readFileSync(path.join(upstream, "resources/countries.json"), "utf8"));
const nameOf = Object.fromEntries(countries.map((c) => [c.code, c.name]));
const codes = CODES.filter((c) => fs.existsSync(path.join(upstream, "resources/flags", `${c}.svg`)));
const rows = Math.ceil(codes.length / COLS);
const atlas = Buffer.alloc(COLS * W * rows * H * 4);

codes.forEach((code, i) => {
  const svg = fs.readFileSync(path.join(upstream, "resources/flags", `${code}.svg`), "utf8");
  const probe = new Resvg(svg);
  const scale = Math.max(W / probe.width, H / probe.height); // cover, then crop
  const img = new Resvg(svg, { fitTo: { mode: "zoom", value: scale } }).render();
  const px = img.pixels;
  const ox = Math.floor((img.width - W) / 2), oy = Math.floor((img.height - H) / 2);
  const cx = (i % COLS) * W, cy = Math.floor(i / COLS) * H;
  for (let y = 0; y < H; y++) {
    for (let x = 0; x < W; x++) {
      const s = ((y + oy) * img.width + (x + ox)) * 4;
      const d = ((cy + y) * COLS * W + (cx + x)) * 4;
      atlas[d] = px[s]; atlas[d + 1] = px[s + 1]; atlas[d + 2] = px[s + 2]; atlas[d + 3] = px[s + 3];
    }
  }
});

const lua = `-- AUTO-GENERATED by tools/pack-flags.mjs from OpenFrontIO resources/flags
-- (CC BY-SA 4.0, attribution: OpenFront). Do not edit.
return {
\tw = ${W},
\th = ${H},
\tcols = ${COLS},
\tcodes = { ${codes.map((c) => JSON.stringify(c)).join(", ")} },
\tnames = {
${codes.map((c) => `\t\t[${JSON.stringify(c)}] = ${JSON.stringify(nameOf[c] ?? c.toUpperCase())},`).join("\n")}
\t},
\trgba = "${atlas.toString("base64")}",
}
`;
fs.writeFileSync(path.resolve(here, "../src/shared/Data/Flags.luau"), lua);
console.log(`Flags.luau: ${codes.length} flags, ${(lua.length / 1024).toFixed(0)} KB`);
