// Packs OpenFrontIO data files into Luau modules.
//
// Usage: node tools/pack-data.mjs
//
// resources/tribeNameThemes.json -> src/server/Core/Data/TribeNameThemes.luau
// (OpenFrontIO /resources is CC BY-SA 4.0 — see NOTICE.md.)

import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const here = path.dirname(fileURLToPath(import.meta.url));
const upstreamRoot = process.env.OPENFRONT_DIR ?? path.resolve(here, "../../OpenFrontIO");
const outDir = path.resolve(here, "../src/server/Core/Data");

const luaStr = (s) => JSON.stringify(String(s));
const list = (arr) => `{ ${arr.map(luaStr).join(", ")} }`;

const themes = JSON.parse(fs.readFileSync(path.join(upstreamRoot, "resources/tribeNameThemes.json"), "utf8"));
const rows = Object.entries(themes).map(
  ([name, t]) => `\t[${luaStr(name)}] = {\n\t\tprefixes = ${list(t.prefixes)},\n\t\tsuffixes = ${list(t.suffixes)},\n\t},`,
);
const lua = `-- AUTO-GENERATED by tools/pack-data.mjs from OpenFrontIO resources/tribeNameThemes.json.
-- (c) OpenFront, CC BY-SA 4.0. Do not edit by hand.
return {
${rows.join("\n")}
}
`;
fs.mkdirSync(outDir, { recursive: true });
fs.writeFileSync(path.join(outDir, "TribeNameThemes.luau"), lua);
console.log(`TribeNameThemes.luau: ${Object.keys(themes).length} themes`);
