// Packs upstream resources/atlases/unit-atlas.png (CC BY-SA 4.0) — the
// grayscale mobile-unit sprites UnitPass colourises — into a Luau module.
//
// Usage (once: `npm install` in tools/):
//   node tools/pack-sprites.mjs [path/to/OpenFrontIO]
// Writes src/shared/Data/Sprites.luau:
//   { cell = 13, order = { ... }, width, height, rgba = base64 }

import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";
import { PNG } from "pngjs";

const here = path.dirname(fileURLToPath(import.meta.url));
const upstream = process.argv[2] ?? process.env.OPENFRONT_DIR ?? path.resolve(here, "../../OpenFrontIO");

// UnitPass UNIT_ORDER (atlas column order).
const ORDER = [
  "Transport",
  "Trade Ship",
  "Warship",
  "Atom Bomb",
  "Hydrogen Bomb",
  "MIRV",
  "SAMMissile",
  "Shell",
  "MIRV Warhead",
  "TrainEngine",
  "TrainCarriage",
  "TrainCarriageLoaded",
];

const png = PNG.sync.read(fs.readFileSync(path.join(upstream, "resources/atlases/unit-atlas.png")));
const cell = png.height;
if (png.width !== cell * ORDER.length) throw new Error(`unexpected atlas size ${png.width}x${png.height}`);

const lua = `-- AUTO-GENERATED by tools/pack-sprites.mjs from upstream OpenFrontIO
-- resources/atlases/unit-atlas.png (CC BY-SA 4.0, © OpenFront and Contributors). Do not edit.
-- ${ORDER.length} columns of ${cell}x${cell} grayscale sprites, straight RGBA, base64.
return {
\tcell = ${cell},
\twidth = ${png.width},
\theight = ${png.height},
\torder = { ${ORDER.map((o) => JSON.stringify(o)).join(", ")} },
\trgba = "${Buffer.from(png.data).toString("base64")}",
}
`;
const dst = path.resolve(here, "../src/shared/Data/Sprites.luau");
fs.writeFileSync(dst, lua);
console.log(`wrote ${dst} (${png.width}x${png.height})`);
