// Packs OpenFrontIO's default theme colours into a Luau module, using the
// original colord library so every derived colour matches upstream exactly.
//
// Usage: node tools/pack-colors.mjs
//
// Output: src/shared/Data/ThemeColors.luau
//   * palettes (human / nation / classicBot / fallback / team) as RGB
//   * CIEDE2000 distance matrices for the human and nation pools (what
//     ColorAllocator.selectDistinctColorIndex compares; only needed while
//     fewer than 50 colours are assigned, i.e. within the primary pool)
//   * border colour for every palette colour: borderColor(c) from
//     ThemeProvider (HSL lightness scale, then colord .darken(borderDarken))

import fs from "node:fs";
import path from "node:path";
import { createRequire } from "node:module";
import { fileURLToPath } from "node:url";

const here = path.dirname(fileURLToPath(import.meta.url));
const upstream = process.env.OPENFRONT_DIR ?? path.resolve(here, "../../OpenFrontIO");
const require = createRequire(path.join(upstream, "package.json"));
const { colord, extend } = require("colord");
extend([require("colord/plugins/lab"), require("colord/plugins/lch")]);

const theme = JSON.parse(fs.readFileSync(path.join(upstream, "src/client/render/gl/default-theme.json"), "utf8"));

function borderColor(c) {
  let out = c;
  if (theme.borderLightnessScale !== 1) {
    const hsl = out.toHsl();
    out = colord({ ...hsl, l: hsl.l * theme.borderLightnessScale });
  }
  if (theme.borderDarken !== 0) out = out.darken(theme.borderDarken);
  return out;
}

const rgb = (c) => {
  const { r, g, b } = c.toRgb();
  return `{ ${r}, ${g}, ${b} }`;
};
const entry = (hex) => {
  const c = colord(hex);
  return `{ rgb = ${rgb(c)}, border = ${rgb(borderColor(c))} }`;
};
const list = (hexes) => `{\n${hexes.map((h) => `\t\t${entry(h)},`).join("\n")}\n\t}`;

function deltaMatrix(hexes) {
  const cs = hexes.map((h) => colord(h));
  const rows = cs.map((a) => cs.map((b) => a.delta(b)));
  // Row-major flat list, full double precision.
  return `{ ${rows.flat().map((v) => (Number.isInteger(v) ? String(v) : v.toPrecision(17))).join(", ")} }`;
}

// ThemeProvider generateTeamColors: 64 LCH variations per team (Bot: 1).
function generateTeamColors(base) {
  const lch = base.toLch();
  const goldenAngle = 137.508;
  return Array.from({ length: 64 }, (_, index) => {
    if (index === 0) return base;
    const hueShift = ((index * goldenAngle) % 12) - 6;
    const h = (lch.h + hueShift + 360) % 360;
    const chromaFactor = 1.0 + 0.1 * Math.sin(index * 0.7);
    const c = Math.max(10, Math.min(130, lch.c * chromaFactor));
    const lightOffset = 18 * Math.sin(index * goldenAngle * (Math.PI / 180));
    const l = Math.max(25, Math.min(80, lch.l + lightOffset));
    return colord({ l, c, h });
  });
}
const teamPalettes = Object.entries(theme.teamColors)
  .map(([name, hex]) => {
    const base = colord(hex);
    const colors = name === "Bot" ? [base] : generateTeamColors(base);
    const rows = colors.map((c) => `\t\t\t{ rgb = ${rgb(c)}, border = ${rgb(borderColor(c))} },`).join("\n");
    return `\t\t[${JSON.stringify(name)}] = {\n${rows}\n\t\t},`;
  })
  .join("\n");

const teams = Object.entries(theme.teamColors)
  .map(([name, hex]) => `\t\t[${JSON.stringify(name)}] = ${entry(hex)},`)
  .join("\n");

const lua = `-- AUTO-GENERATED by tools/pack-colors.mjs from OpenFrontIO default-theme.json
-- using colord (same math as upstream ThemeProvider / ColorAllocator). Do not edit.
return {
\tborderDarken = ${theme.borderDarken},
\thuman = ${list(theme.humanColors)},
\tnation = ${list(theme.nationColors)},
\tclassicBot = ${list(theme.classicBotColors)},
\tfallback = ${list(theme.fallbackColors)},
\tteam = {
${teams}
\t},
\t-- Per-team player variations (teamColorForPlayer: simpleHash(id) % n).
\tteamPalettes = {
${teamPalettes}
\t},
\t-- CIEDE2000 (colord .delta) between pool colours, row-major.
\thumanDelta = ${deltaMatrix(theme.humanColors)},
\tnationDelta = ${deltaMatrix(theme.nationColors)},
\tclassicBotDelta = ${deltaMatrix(theme.classicBotColors)},
\tfocusedBorder = ${rgb(colord(theme.focusedBorderColor))},
\tspawnHighlight = ${rgb(colord(theme.spawnHighlightColor))},
}
`;
const outDir = path.resolve(here, "../src/shared/Data");
fs.mkdirSync(outDir, { recursive: true });
fs.writeFileSync(path.join(outDir, "ThemeColors.luau"), lua);
console.log(
  `ThemeColors.luau: human ${theme.humanColors.length}, nation ${theme.nationColors.length}, fallback ${theme.fallbackColors.length}, ${(lua.length / 1024).toFixed(0)} KB`,
);
