// Writes src/shared/Data/Emojis.luau from upstream src/core/Util.ts emojiTable
// (exact code points, incl. variation selectors and ZWJ sequences).
//   node tools/pack-emojis.mjs [path/to/OpenFrontIO]

import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const here = path.dirname(fileURLToPath(import.meta.url));
const upstream = process.argv[2] ?? process.env.OPENFRONT_DIR ?? path.resolve(here, "../../OpenFrontIO");
const src = fs.readFileSync(path.join(upstream, "src/core/Util.ts"), "utf8");
const m = /export const emojiTable = \[([\s\S]*?)\] as const;/.exec(src);
if (!m) throw new Error("emojiTable not found");
const rows = JSON.parse("[" + m[1].replace(/,\s*$/, "") + "]");
const esc = (s) => [...s].map((ch) => "\\u{" + ch.codePointAt(0).toString(16) + "}").join("");

let lua = `-- AUTO-GENERATED by tools/pack-emojis.mjs from upstream src/core/Util.ts emojiTable.
-- flat[id + 1] is upstream flattenedEmojiTable[id] (ids are 0-based on the wire).
local rows = {
`;
for (const r of rows) lua += `\t{ ${r.map((e) => `"${esc(e)}"`).join(", ")} },\n`;
lua += `}
local flat = {}
for _, row in rows do
\tfor _, e in row do
\t\ttable.insert(flat, e)
\tend
end
local index = {}
for i, e in flat do
\tindex[e] = i - 1
end
return { rows = rows, flat = flat, index = index }
`;
fs.writeFileSync(path.resolve(here, "../src/shared/Data/Emojis.luau"), lua);
console.log(`${rows.flat().length} emojis`);
