// Packs an OpenFrontIO map into a Luau ModuleScript.
//
// Usage: node tools/pack-map.mjs <mapDir> [<mapDir> ...]
//   e.g. node tools/pack-map.mjs world europe
//
// Reads ../OpenFrontIO/resources/maps/<mapDir>/{manifest.json,map4x.bin,map16x.bin}
// and writes src/shared/Maps/<Id>.luau. Terrain is zstd-compressed and
// base64-encoded; the game decodes it with EncodingService (see MapLoader).
//
// We ship the Compact variant (map4x as the game map, map16x as the minimap),
// mirroring GameMapSize.Compact in OpenFrontIO's TerrainMapLoader.ts, including
// its floor(coord / 2) scaling of nation coordinates and team spawn areas.
//
// Map data is (c) OpenFront, licensed CC BY-SA 4.0 — see NOTICE.md.

import fs from "node:fs";
import path from "node:path";
import zlib from "node:zlib";
import { fileURLToPath } from "node:url";

const here = path.dirname(fileURLToPath(import.meta.url));
const upstreamMaps =
  process.env.OPENFRONT_MAPS ??
  path.resolve(here, "../../OpenFrontIO/resources/maps");
const outDir = path.resolve(here, "../src/shared/Maps");

function packTerrain(bin, meta, label) {
  if (bin.length !== meta.width * meta.height) {
    throw new Error(
      `${label}: ${bin.length} bytes, expected ${meta.width}x${meta.height}`,
    );
  }
  const z = zlib.zstdCompressSync(bin, {
    params: { [zlib.constants.ZSTD_c_compressionLevel]: 19 },
  });
  if (Buffer.compare(zlib.zstdDecompressSync(z), bin) !== 0) {
    throw new Error(`${label}: zstd round-trip mismatch`);
  }
  return Buffer.from(z).toString("base64");
}

const half = (v) => Math.floor(v / 2);

// Luau string literal. Names come from upstream manifests, so escape properly.
function luaStr(s) {
  return JSON.stringify(String(s));
}

function nationsLua(list) {
  if (!list || list.length === 0) return "{}";
  const rows = list.map((n) => {
    const parts = [`name = ${luaStr(n.name)}`];
    if (n.flag !== undefined) parts.push(`flag = ${luaStr(n.flag)}`);
    if (n.coordinates !== undefined) {
      parts.push(
        `coordinates = { ${half(n.coordinates[0])}, ${half(n.coordinates[1])} }`,
      );
    }
    return `\t\t{ ${parts.join(", ")} },`;
  });
  return `{\n${rows.join("\n")}\n\t}`;
}

function spawnAreasLua(areas) {
  if (!areas) return "nil";
  const keys = Object.keys(areas);
  const rows = keys.map((k) => {
    const list = areas[k]
      .map(
        (a) =>
          `{ x = ${half(a.x)}, y = ${half(a.y)}, width = ${Math.max(1, half(a.width))}, height = ${Math.max(1, half(a.height))} }`,
      )
      .join(", ");
    return `\t\t[${luaStr(k)}] = { ${list} },`;
  });
  return `{\n${rows.join("\n")}\n\t}`;
}

function packMap(dir) {
  const src = path.join(upstreamMaps, dir);
  const manifest = JSON.parse(
    fs.readFileSync(path.join(src, "manifest.json"), "utf8"),
  );
  const map = manifest.map4x;
  const mini = manifest.map16x;
  const terrain = packTerrain(
    fs.readFileSync(path.join(src, "map4x.bin")),
    map,
    `${dir}/map4x`,
  );
  const miniTerrain = packTerrain(
    fs.readFileSync(path.join(src, "map16x.bin")),
    mini,
    `${dir}/map16x`,
  );
  // Module name must be a valid Roblox instance name; ids are like "World".
  const id = String(manifest.id ?? manifest.name).replace(/[^A-Za-z0-9_]/g, "");

  const lua = `-- AUTO-GENERATED by tools/pack-map.mjs — do not edit by hand.
-- Source: OpenFrontIO resources/maps/${dir} (Compact size: map4x + map16x)
-- Map data (c) OpenFront, licensed CC BY-SA 4.0. See NOTICE.md.
return {
\tid = ${luaStr(id)},
\tname = ${luaStr(manifest.name)},
\tcategories = { ${(manifest.categories ?? []).map(luaStr).join(", ")} },
\twidth = ${map.width},
\theight = ${map.height},
\tnumLandTiles = ${map.num_land_tiles},
\tminiWidth = ${mini.width},
\tminiHeight = ${mini.height},
\tminiNumLandTiles = ${mini.num_land_tiles},
\tnations = ${nationsLua(manifest.nations)},
\tadditionalNations = ${nationsLua(manifest.additionalNations)},
\tteamGameSpawnAreas = ${spawnAreasLua(manifest.teamGameSpawnAreas)},
\t-- zstd + base64 terrain bytes (1 byte per tile, row-major).
\tterrain = "${terrain}",
\tminiTerrain = "${miniTerrain}",
}
`;
  fs.mkdirSync(outDir, { recursive: true });
  const outFile = path.join(outDir, `${id}.luau`);
  fs.writeFileSync(outFile, lua);
  console.log(
    `${dir} -> ${path.relative(process.cwd(), outFile)}  ${map.width}x${map.height}  ${(lua.length / 1024).toFixed(0)} KB`,
  );
}

const dirs = process.argv.slice(2);
if (dirs.length === 0) {
  console.error("usage: node tools/pack-map.mjs <mapDir> [<mapDir> ...]");
  process.exit(1);
}
for (const d of dirs) packMap(d);
